name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag liordaniel/final_project_devops:${{ github.run_number }}-${{ github.sha }}
      
    - name: push docker image to registry
      run: docker push liordaniel/final_project_devops:${{ github.run_number }}-${{ github.sha }}
